<a href="https://colab.research.google.com/github/Cyber-Mood/Mahmud-PDS/blob/main/PDS_Assignment_1(Mahmud).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Short Questions

**1. How many basic data types are there in Python?**  
**A.** Python has 8 basic data types: Numeric, Text, Sequence, Mapping, Set, Boolean, None.

**2. How do you create a list in Python? Provide an example.**
```python
my_list = [55, 22, 3, "biryani", "pulao"]
```
**3. How do you create a variable in Python and assign the value 15 to it?**
```python
my_variable = 15
```
**4. What is the difference between ‘=’ and ‘==’ in Python?**  
- **'='** assigns a value to a variable, e.g., `x = 5`
- **'=='** checks if two values are equal, e.g., `x == 5`.

**5. How do you access the first element of a list named ‘my_list’?**
```python
my_list = [55, 22, 3, "biryani", "pulao"]
my_list[0]
```
**6. What does the ‘len()’ function do in Python?**  
The `len()` function returns the number of items in an object, like the length of a list, string, or other iterable.
```python
length = len(my_list)
```

**7. How do you write a docstring in Python?**  
In Python, a **docstring** is written using triple quotes (`"""` or `'''`) and is placed below a function, class, or module to describe its purpose.
```python
"""This is a docstring."""
#similar to comment
```
**8. What is the difference between a list and a tuple?**  
- **List**: Mutable (can be changed), defined with `[]`.
- **Tuple**: Immutable (cannot be changed), defined with `()`.

**9.How do you cast an integer to a string in Python?**  
**A.** Use the `str()` function to cast an integer to a string.
```python
str_value = str(15)
```
**10. What is the difference between ‘=’ and ‘==’ in Python?**  
- **'='** assigns a value to a variable, e.g., `x = 5`
- **'=='** checks if two values are equal, e.g., `x == 5`.

**11. Print the output of the following code:**  
s = "Introduction to python"  
print(s[:8:2])  
print(s[::-1])  
print(s[1::2])  
**Output**  
1. Ito  
2. nohtyp ot noitcudortnI  
3. ntoucot yhn  

**12. What is the purpose of the %timeit magic command?**  
**A.** The `%timeit` magic command in IPython is used to measure the execution time of a statement or expression, running it multiple times for more accurate timing.

**13. What is the purpose of a Python comment, and how do you write a single-line comment in Python?**  
**A.** A Python comment is used to explain code or make it more readable.

**Single-line comment**: Start with `#`.
```python
# Ma'am assignment korte bhalo lage na 😭.
```
**14. What is the difference between %time and %timeit in IPython?**  
- **%time**: Measures the execution time of a single run of a statement.
- **%timeit**: Runs the statement multiple times and provides an average execution time for more accurate results.

**15. What is the difference between List and Tuple in Python?**
- **List**: Mutable (can be changed), defined with `[]`.
- **Tuple**: Immutable (cannot be changed), defined with `()`.

**16. How do you access the last element of a list named ‘my_list’?**
```python
my_list = [55, 22, 3, "biryani", "pulao"]]
my_list[-1]
```

**17. What do you mean by data type? Give examples.**  
**A.** A data type defines the kind of value a variable can hold and what operations can be performed on it.
- **int**: Integer values (e.g., `5`)
- **float**: Decimal numbers (e.g., `3.14`)
- **str**: Strings (e.g., `"hello"`)
- **list**: Ordered collections (e.g., `[1, 2, 3]`)
- **dict**: Key-value pairs (e.g., `{'name': 'Alice', 'age': 25}`)

**18. What is the difference between an Array and Dictionary?**
- **Array**: An ordered collection of items, typically of the same data type, accessed by numerical indices. Example: `[1, 2, 3]`.

- **Dictionary**: An unordered collection of key-value pairs, where each key is unique and used to access its corresponding value. Example: `{'name': 'Alice', 'age': 25}`.

**19. What is the difference between / and // in Python?**  
- **/**: Performs floating-point (true) division, returning a float.  
  Example: `5 / 2` results in `2.5`.

- **//**: Performs floor division, returning the largest integer less than or equal to the result.  
  Example: `5 // 2` results in `2`.

**20. How do you define a function in Python? Write an example.**  
**A.** To define a function in Python, `def` keyword is used followed by the function name and parentheses.
```python
def greet():
    print("Ki khobor mama?!!")
```

**21. How do you create a NumPy array named numbers from a list of integers [1, 2, 3, 4, 5, 6, 7, 8] and print the elements using slicing with the notation numbers[1::2]?**  
**A.** First import the NumPy library, then use function.
```python
import numpy as np
numbers = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print(numbers[1::2])
#Output: [2 4 6 8]
```
**22. Explain split() and join() functions in Python?**
- **split()**: This function splits a string into a list based on a specified delimiter (default is whitespace).
```python
sentence = "Shunamoni Shunamoni bosho bosho"
words = sentence.split()
```
```
#output
['Shunamoni', 'Shunamoni', 'bosho', 'bosho']
```
- **join()**: This function concatenates a list of strings into a single string, using a specified delimiter.  
```python
words = ['Shunamoni', 'Shunamoni', 'bosho', 'bosho']
sentence = " ".join(words)
```
```
#output
'Shunamoni Shunamoni bosho bosho'
```

**23. How do you create a Python dictionary with the keys 'name', 'age', 'Course', and corresponding values 'Alice', 25, and 'PDS'?**
```python
student_info = {'name': 'Alice', 'age': 25, 'Course': 'PDS'}
```

**24. What is the difference between List and Tuple?**
- **List**: Mutable (can be changed), defined with `[]`.
- **Tuple**: Immutable (cannot be changed), defined with `()`.

**25. How do you print the summation of all the numbers from 1 to 101?**
``` python
total = sum(range(1, 102))
print(total)
```

**26. In Python, what is docstrings?**  
**A.** In Python, **docstrings** are special comments used to describe the purpose and usage of functions, classes, or modules. They are written as a string literal right below the function or class definition and can be accessed via the `__doc__` attribute.
```python
def greet():
  """greet function will print a message""" <-- Docstring
    print("Murrubbi Murrubbi uhmmm uhmmm!!")
```

**27. What is the output of print(2 * 2 ** 5)?**
```
64
```

**28. How would you run a cell of code from a different file using IPython magic commands?**  
**A.** Use the **`%run`** command followed by the filename to execute a code file in IPython.
```python
%run my_script.py
```

**29. What is the output of the following code?**   
         print(bool(3!=4))  
**A.** The output is `True`, because `3 != 4` is `True`.


**30. How do you create a Dictionary in Python? Provide an example.**
**A.** To create a dictionary in Python, use curly braces {} with key-value pairs separated by colons.
```python
st_dict = {'name': 'Jenifa', 'age': 24, 'Course': 'Cooking and Baking'}
```

**31. How do you create a Third Party function in Python?**  
**A.** To create a third-party function in Python, you typically need to install an external library and then import it into your code.
```bash
# Install the library (if not already installed)
pip install requests
```
```python
# Import and use the third-party function
import requests
response = requests.get('https://catalog.data.gov/dataset/')
print(response.csv())  # Prints the CSV response from the API
```

**32. Which one is Mutable - List or Tuple in Python?**  
**A.** **List** is mutable; **Tuple** is immutable.

**33. What does the %timeit magic command do in IPython?**  
**A.** The `%timeit` magic command in IPython measures the execution time of a statement by running it multiple times and providing an average execution time for more accurate results.

**34. What does the %timeit magic command do in IPython?**  
**A.** The `%timeit` magic command in IPython measures the execution time of a statement by running it multiple times and providing an average execution time for more accurate results.

**35. How do you create a NumPy array in Python? Give an example.**  
```python
import numpy as np
numbers = np.array([1, 2, 3, 4, 5])
```
**36. Explain the difference between “is” and “==” in Python.**  
- **`is`**: Checks if two variables refer to the same object in memory (identity comparison).

- **`==`**: Checks if the values of two variables are equal (value comparison).

**37. Explain the difference between mutable and immutable objects in Python.**  
- **Mutable Objects:** These can be changed after their creation. You can modify, add, or remove elements. Examples include lists, dictionaries, and sets.

- **Immutable Objects:** These cannot be changed once created. Any modification creates a new object instead. Examples include strings, tuples, and frozensets.

**38. What is a function in Python, and why are functions used? Give an example.**  
**A.** A **function** in Python is a block of reusable code that performs a specific task. Functions are used to organize code, avoid repetition, and improve readability and maintainability.
```python
def add(a, b):
    return a + b
result = add(3, 5)  # Calls the function and stores the result
print(result)  # Output: 8
```




#MCQs


1. a) list = [1, 2, 3]
2. b) 8
3. d) Tuple
4. d) All
5. b) def
6. b) 4
7. b) variable_1
8. c) print("Hello World")
9. d) All of the above
10. b) 2
11. c) To do nothing and move to the next line of code
12. c) if
13. d) No output
14. a) Terminates the loop
15. c) #
16. b) False
17. a) input()
18. b) 18
19. d) real
20. d) type(var)
21. a) Measures the execution time of the code
22. d) %lprun
23. a) %memit
24. a) np.array([1, 2, 3, 4])
25. b) [2, 3]

#Broad Questions

1. Write a Python program to find the factorial of a number using recursion.

In [ ]:
def factorial(n):
    if n == 0 or n == 1:
        return 1
    else:
        return n * factorial(n - 1)
n = 7
print(f"The factorial of {n} is {factorial(n)}")

The factorial of 7 is 5040


2. Write a Python program to find Anagram Check.

In [ ]:
def are_anagrams(str1, str2):
    str1 = str1.replace(" ", "").lower()
    str2 = str2.replace(" ", "").lower()

    return sorted(str1) == sorted(str2)
print(are_anagrams("Listen", "Silent"))

True


3. Write a Python program using a for loop that:  
i. Prints the multiplication table for a given number ‘n’.  
ii. Calculates the factorial of a given number.

In [ ]:
def multiplication_table(n):
    for i in range(1, 11):
        print(f"{n} x {i} = {n * i}")

def factorial(n):
    fact = 1
    for i in range(1, n + 1):
        fact *= i
    return fact

n = int(input("Enter a number: "))
multiplication_table(n)
print(f"\nFactorial of {n} is {factorial(n)}")

Enter a number: 5
5 x 1 = 5
5 x 2 = 10
5 x 3 = 15
5 x 4 = 20
5 x 5 = 25
5 x 6 = 30
5 x 7 = 35
5 x 8 = 40
5 x 9 = 45
5 x 10 = 50
Factorial of 5 is 120


4. You are given a list of positive integers containing all numbers from 1 to n except one missing value x. Write a Python program to find the missing value x in the list.

In [ ]:
def missing_number(nums):
    n = len(nums) + 1
    return n * (n + 1) // 2 - sum(nums)

nums = [1, 2, 4, 5, 6]
print(f"The missing number is: {missing_number(nums)}")

The missing number is: 3


5. Write a Python program to Count Words in a Sentence.

In [ ]:
def count_words(sentence):
    return len(sentence.split())

sentence = input("Enter a sentence: ")
print("Number of words:", count_words(sentence))

Enter a sentence: Friday te presentation
Number of words: 3


6. i. Define a function check_odd_even(n) that takes n as input and checks if
it is even or odd.  
ii. Define a function fibonacci(n) that takes n as input and prints the n-th Fibonacci number.

In [ ]:
#i) odd even
def check_odd_even(n):
    if n % 2 == 0:
        print(f"{n} is even\n")
    else:
        print(f"{n} is odd\n")

#ii) fibonacci
def fibonacci(n):
    a, b = 0, 1
    for _ in range(n):
        a, b = b, a + b
    print(f"The {n}-th Fibonacci number is: {a}")

check_odd_even(10)
fibonacci(10)

10 is even

The 10-th Fibonacci number is: 55


7. Write a program using the ternary operator where,  
i. Given an age, determine the category of the age (i.e., child, teenager, adult).  
ii. Check if a given number is positive, negative, or zero.

In [ ]:
# i) Category
age = int(input("Enter age: "))
category = "child" if age < 13 else "teenager" if age < 18 else "adult"
print(f"Category: {category}\n")

# ii) Check number
number = int(input("Enter a number: "))
status = "positive" if number > 0 else "negative" if number < 0 else "zero"
print(f"Number is: {status}")


Enter age: 23
Category: adult

Enter a number: 20
Number is: positive


8. Given a dictionary of product prices:  
prices = { 'apple': 30, 'banana': 10, 'orange': 60, 'grape': 55, 'mango': 20}  
Write a Python program to  
i. Change the pricing of a product.  
ii. Add a new product to the inventory with its price.  
iii. Determine and print whether each product is "Expensive" or "Affordable".

In [ ]:
prices = {'apple': 30, 'banana': 10, 'orange': 60, 'grape': 55, 'mango': 20}

# i. Change the pricing of a product
prices['apple'] = 35

# ii. Add a new product to the inventory with its price
prices['kiwi'] = 50

# iii. Determine if each product is "Expensive" or "Affordable"
for product, price in prices.items():
    status = "Expensive" if price > 40 else "Affordable"
    print(f"{product}: {status}")


apple: Affordable
banana: Affordable
orange: Expensive
grape: Expensive
mango: Affordable
strawberry: Expensive


9. Write a Python program to check if a given number is a perfect number. A perfect number is a
positive integer that is equal to the sum of its proper divisors (excluding itself).

In [ ]:
def is_perfect_number(n):
    return sum(i for i in range(1, n) if n % i == 0) == n

number = int(input("Enter a number: "))
print(f"{number} is a perfect number."
if is_perfect_number(number)
else f"{number} is not a perfect number.")

Enter a number: 6
6 is a perfect number.


10. Write a Python program to find the maximum difference between two elements in a given list.

In [ ]:
def max_difference(nums):
    return max(nums) - min(nums) if len(nums) >= 2 else "List must have at least two elements."

numbers = [23, 10, 6, 1, 8]
print("The maximum difference is:", max_difference(numbers))

The maximum difference is: 22


11. Write a Python program using list comprehension to create a new list that contains the squares of the numbers that are divisible by 3 but not by 5. Then, print the resulting list.

In [ ]:
numbers = range(1, 31)

squares = [x**2 for x in numbers if x % 3 == 0 and x % 5 != 0]

print("Squares of numbers divisible by 3 but not by 5:\n", squares)

Squares of numbers divisible by 3 but not by 5:
 [9, 36, 81, 144, 324, 441, 576, 729]


12. Write Python code for the following tasks:  
i. Create a 3x3 NumPy array filled with random integers. Compute the mean of all the elements in the array and print it.  
ii. Create a 2D NumPy array with shape (4,4). Split the array into 2 equal- sized horizontal slices.

In [ ]:
import numpy as np

# Task i: Create a 3x3 array of random integers and compute the mean
array3 = np.random.randint(1, 100, size=(3, 3))
mean_value = np.mean(array3)
print("Mean of 3x3 array:", mean_value)

# Task ii: Create a 4x4 array and split it into 2 horizontal slices
array4 = np.arange(1, 17).reshape(4, 4)
slices = np.split(array4, 2)
print("Horizontal slices:\n", slices)


Mean of 3x3 array: 54.333333333333336
Horizontal slices:
 [array([[1, 2, 3, 4],
       [5, 6, 7, 8]]), array([[ 9, 10, 11, 12],
       [13, 14, 15, 16]])]


13. Define a function factorial(n) that takes an integer n as input and returns the factorial of n.

In [ ]:
def factorial(n):
    return 1 if n in (0, 1) else n * factorial(n - 1)

n = int(input("Enter a number: "))
print(factorial(n))

Enter a number: 5
120


14. You are provided with the following Python code that is supposed to compute the sum of all positive integers up to a given number n. However, the code has an error that prevents it from running correctly.
``` python
def sum_up_to(n):  
  total = 0  
  for i in range(n):  
    total += i  
return total
print(sum_up_to(5))
```
Your task is to:  
i. Use %xmode to display detailed error messages.  
ii. Debug and correct the code accordingly.  
iii. Provide a brief explanation of the error and your fix using Python Comments.

In [ ]:
%xmode verbose

Exception reporting mode: Verbose


In [ ]:
def sum_up_to(n):
    total = 0
    for i in range(1, n + 1):
        total += i
    return total

print(sum_up_to(5))

15


In [ ]:
# Explanation:
# The original code used `range(n)`, which iterates from 0 to n-1,
# resulting in the sum being calculated as 0 + 1 + 2 + 3 + 4.
# To fix this, I changed `range(n)` to `range(1, n + 1)`, which
# ensures that the loop starts at 1 and includes n in the sum.

15. Write a Python function that generates a list of numbers from 1 to n (inclusive) and returns a new list where each number is replaced by its classification:  
i. "Even" if the number is even.  
ii. "Odd" if the number is odd.  
iii. "Multiple of 2" if the number is a multiple of 2.  
iv. "Even and Multiple of 5" if the number is both even and a multiple of 5.

In [ ]:
def classify_numbers(n):
    classifications = []
    for i in range(1, n + 1):
        if i % 2 == 0 and i % 5 == 0:
            classifications.append("Even and Multiple of 5")
        elif i % 2 == 0:
            classifications.append("Even")
        elif i % 2 == 1:
            classifications.append("Odd")
        if i % 2 == 0:
            classifications[-1] = "Multiple of 2"
    return classifications

n = 5
result = classify_numbers(n)
print(result)


['Odd', 'Multiple of 2', 'Odd', 'Multiple of 2', 'Odd']


16. Write a Python function that performs the following operations on a given list of mixed
data types:  
i. Convert all elements of the list to strings.  
ii. Convert the list into a tuple.  
iii. Create a dictionary where the keys are the indices of the tuple elements and the values are the corresponding elements.  
Instructions:  
Implement the function to perform these tasks. Your function should return the list of
strings, tuple and dictionary.  
Test your function with a sample list: [1, 4.56, "Python",False].

In [ ]:
def mixed_list(data):
    # 1: Convert all elements to strings
    string_list = [str(item) for item in data]

    # 2: Convert the list to a tuple
    data_tuple = tuple(string_list)

    # 3: Create a dictionary with indices as keys and tuple elements as values
    data_dict = {index: value for index, value in enumerate(data_tuple)} #enumaerate() to show index with value

    # Return the list of strings, the tuple, and the dictionary
    return string_list, data_tuple, data_dict

sample_list = [1, 4.56, "Python", False]
result = mixed_list(sample_list)
print("List of Strings:", result[0]) #diff result to show diff output, otherwise it will print the same
print("\nTuple:", result[1])
print("\nDictionary:", result[2])


List of Strings: ['1', '4.56', 'Python', 'False']

Tuple: ('1', '4.56', 'Python', 'False')

Dictionary: {0: '1', 1: '4.56', 2: 'Python', 3: 'False'}


17. Write Python code for the following tasks:  
i. Create a 4x5 array filled with 'Python'.  
ii. Create a 3x3 array of random integers in the interval [5, 10).  
iii. You have a 4x3 NumPy array. Use the reshape method to change its shape to 3x4.  
iv. Create a 2D NumPy array with shape (3, 3). Split this array into 2 equal-sized vertical slices.  
v. Given two NumPy arrays, a = np.array([4, 5, 6]) and b = np.array([7,8,9]), perform the following operations and provide the results:  
Element-wise: addition of a and b, subtraction of a from b, multiplication of a and b and division of b by a.

In [ ]:
import numpy as np

# i: 4x5 array filled with 'Python'
array_python = np.full((4, 5), 'Python')
print("i) 4x5 Array filled with 'Python':\n", array_python)

# ii: 3x3 array of random integers in the interval (5, 10)
array_random = np.random.randint(5, 10, (3, 3))
print("\n ii) 3x3 Array of random integers in (5, 10):\n", array_random)

# iii: Reshaping a 4x3 array to 3x4
array_reshape = np.arange(12).reshape(4, 3)
new_array = array_reshape.reshape(3, 4)
print("\n iii) Reshaped 4x3 Array to 3x4:\n", new_array)

# iv: Split a 3x3 array into 2 equal-sized vertical slices
array_split = np.arange(1, 10).reshape(3, 3)
vertical_slices = np.hsplit(array_split, 3)
print("\n iv) Vertical slices of 3x3 Array:\n", vertical_slices)

# v: Perform element-wise operations on arrays a and b
a = np.array([4, 5, 6])
b = np.array([7, 8, 9])
addition = a + b
subtraction = b - a
multiplication = a * b
division = b / a

print("v) \nElement-wise Addition:", addition)
print("Element-wise Subtraction:", subtraction)
print("Element-wise Multiplication:", multiplication)
print("Element-wise Division:", division)


i) 4x5 Array filled with 'Python':
 [['Python' 'Python' 'Python' 'Python' 'Python']
 ['Python' 'Python' 'Python' 'Python' 'Python']
 ['Python' 'Python' 'Python' 'Python' 'Python']
 ['Python' 'Python' 'Python' 'Python' 'Python']]

 ii) 3x3 Array of random integers in (5, 10):
 [[9 9 7]
 [9 7 8]
 [5 9 7]]

 iii) Reshaped 4x3 Array to 3x4:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

 iv) Vertical slices of 3x3 Array:
 [array([[1],
       [4],
       [7]]), array([[2],
       [5],
       [8]]), array([[3],
       [6],
       [9]])]
v) 
Element-wise Addition: [11 13 15]
Element-wise Subtraction: [3 3 3]
Element-wise Multiplication: [28 40 54]
Element-wise Division: [1.75 1.6  1.5 ]


18. Given the following NumPy array:  
```
arr = np.array([[3, 2, 4, 1],
[6, 8, 5, 7],
[11, 10, 12, 9]])
```
Perform the following tasks:  
i. Create a boolean mask to identify elements greater than 6. Use this mask to extract the elements from the array.  
ii. Extract the second and third rows from the array using fancy indexing.  
iii. Sort the entire array along the rows and print the sorted array.

In [ ]:
import numpy as np

arr = np.array([[3, 2, 4, 1],
                [6, 8, 5, 7],
                [11, 10, 12, 9]])

# i: boolean mask to identify elements greater than 6
mask = arr > 6
elements = arr[mask]
print("Elements greater than 6:", elements)

# ii: Extract the second and third rows using fancy indexing
rows_extracted = arr[[1, 2]]  # Fancy indexing
print("\nSecond and Third Rows:\n", rows_extracted)

# iii: Sort the entire array along the rows and print the sorted array
sorted_array = np.sort(arr, axis=1)  # Sort along rows
print("\nSorted Array:\n", sorted_array)

Elements greater than 6: [ 8  7 11 10 12  9]

Second and Third Rows:
 [[ 6  8  5  7]
 [11 10 12  9]]

Sorted Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


19. i. Write a program that will take user input of cost price and selling price and determine whether its a loss or a profit.  
ii. Write a program that will check whether the number is an Armstrong number or not. *(The user will provide the integer input)*

In [ ]:
#1
def calculate_profit_loss(cost_price, selling_price):
    if selling_price > cost_price:
        return f"Profit: {selling_price - cost_price}"
    elif selling_price < cost_price:
        return f"Loss: {cost_price - selling_price}"
    return "No Profit, No Loss"

cost_price = float(input("Enter the cost price: "))
selling_price = float(input("Enter the selling price: "))
result = calculate_profit_loss(cost_price, selling_price)
print(result)

Enter the cost price: 55
Enter the selling price: 55
No Profit, No Loss


In [ ]:
#2
def is_armstrong_number(num):
    power = len(str(num))
    return sum(int(digit) ** power for digit in str(num)) == num

number = int(input("Enter an integer: "))
print(f"{number} is an Armstrong number." if is_armstrong_number(number) else f"{number} is not an Armstrong number.")

Enter an integer: 155
155 is not an Armstrong number.


20. i. Write a loop in Python that prints the numbers from 1 to 100.  
ii. How do you create a List in Python? Provide an example.

In [ ]:
#1
for num in range(1, 101):
    print(num)

In [ ]:
#2
meals = ["biryani", "shawarma", "kabsa", "shawaya"]
meals

['biryani', 'shawarma', 'kabsa', 'shawaya']

21. Write a Python function that performs the following operations on a given list of integers:  
i. Remove all duplicate elements from the list while preserving the order of the first occurrence of each element.  
ii. Sort the remaining elements in ascending order.  
iii. Create a new list where each element is the square of the elements from the sorted list.

In [ ]:
def process_list(numbers):
    unique_numbers = []
    for num in numbers:
        if num not in unique_numbers:
            unique_numbers.append(num)

    # Sort the numbers
    unique_numbers.sort()

    # new list with squares of the sorted numbers
    squared_numbers = [num ** 2 for num in unique_numbers]
    return squared_numbers

numbers = [4, 2, 5, 2, 3, 4, 1, 3, 10]
result = process_list(numbers)
print("Squared Numbers:", result)

Squared Numbers: [1, 4, 9, 16, 25, 100]


22. Write a function “min_max_range” that performs the following operations on a 2D NumPy array:  
i. Find the minimum and maximum values in the entire array.   
ii. Find the minimum and maximum values for each row.  
iii. difference between maximum and minimum values for each row.

In [ ]:
import numpy as np

def min_max_range(arr):
    # minimum and maximum values in the entire array
    overall_min = np.min(arr)
    overall_max = np.max(arr)

    # minimum and maximum values for each row
    row_min = np.min(arr, axis=1)
    row_max = np.max(arr, axis=1)

    # difference between maximum and minimum values for each row
    row_difference = row_max - row_min
    return overall_min, overall_max, row_min, row_max, row_difference

arr = np.array([[3, 5, 1], [7, 2, 8], [4, 9, 6]])
overall_min, overall_max, row_min, row_max, row_difference = min_max_range(arr)

print("Overall Min:", overall_min)
print("Overall Max:", overall_max)
print("Row-wise Min:", row_min)
print("Row-wise Max:", row_max)
print("Row-wise Difference:", row_difference)

Overall Min: 1
Overall Max: 9
Row-wise Min: [1 2 4]
Row-wise Max: [5 8 9]
Row-wise Difference: [4 6 5]


23. You are given a 2D NumPy array. Write a function “simple_indexing” that:  
i. Extracts the element at position (0, 0) from the array.  
ii. Extracts the entire second row of the array.  
iii. Extracts the first two elements from the second row of the array

In [ ]:
import numpy as np

def simple_indexing(array):
    element = array[0, 0]

    second_row = array[1]

    # Extract the first two elements from the second row
    element2 = array[1, :2]

    return element, second_row, element2

# Example Usage
array = np.array([[3, 5, 7], [9, 11, 13], [15, 17, 19]])
result = simple_indexing(array)

print("Element at (0, 0):", result[0])
print("Entire second row:", result[1])
print("First two elements of second row:", result[2])


Element at (0, 0): 3
Entire second row: [ 9 11 13]
First two elements of second row: [ 9 11]


24. You are given a list of integers. Write a Python function process_list that performs the following operations:  
i. Remove all duplicate integers from the list.  
ii. Sort the remaining integers in ascending order.  
iii. Replace each integer with its square.

In [ ]:
def process_list(numbers):
    # Remove duplicates using set and sort the unique elements
    num_sort = sorted(set(numbers))

    # Replace each integer with its square
    squared_list = [num ** 2 for num in num_sort]

    return squared_list

numbers = [44, 12, 92, 3, 1, 4, 5, 10, 2, 0, 1]
result = process_list(numbers)
print("Processed List:", result)

Processed List: [0, 1, 4, 9, 16, 25, 100, 144, 1936, 8464]


25. Write a Python program that asks the user(students) for their name, Id and age, then prints a greeting message.

In [ ]:
name = input("Enter your name: ")
student_id = input("Enter your ID: ")
age = input("Enter your age: ")

print(f"\nHi, {name}! Tumar ID {student_id}, ar tumar boyosh {age} bosor. Joldi b1iya kore felo. Eto shomoy nai!!")

Enter your name: Joy
Enter your ID: 080
Enter your age: 23

Hi, Joy! Tumar ID 080, ar tumar boyosh 23 bosor. Joldi b1iya kore felo. Eto shomoy nai!!


26. Write a loop in Python that prints the even numbers from 10 to 100.

In [ ]:
for number in range(10, 101, 2):
    print(number)

10
12
14
16
18
20
22
24
26
28
30
32
34
36
38
40
42
44
46
48
50
52
54
56
58
60
62
64
66
68
70
72
74
76
78
80
82
84
86
88
90
92
94
96
98
100


27. Write a Python program to calculate the length of a given string.

In [ ]:
string = input("Enter a string: ")
print("The length of the string is:", len(string))

Enter a string: joy
The length of the string is: 3


28. Write a python program to calculate the sum of digits of a given number.

In [ ]:
number = int(input("Enter a number: "))

sum_of_digits = 0

while number > 0:
    digit = number % 10
    sum_of_digits += digit
    number //= 10
print("The sum of the digits is:", sum_of_digits)

Enter a number: 123
The sum of the digits is: 6


30. Write a program that can create a new list from a given list where each item in the new list is square of the item of the old list.

In [ ]:
def square_list(old_list):
    new_list = [item ** 2 for item in old_list]
    return new_list

old_list = [1, 2, 3, 4, 5]
print("Old List:", old_list)
print("New List:", square_list(old_list))

Old List: [1, 2, 3, 4, 5]
New List: [1, 4, 9, 16, 25]


31. Write a python program that uses a for loop to iterate over a range of numbers. Start from 10 and decrease by 3 each time until you reach a number less than 0. For each number in the range, print whether it is a positive number or not.

In [ ]:
def iterate_numbers():
    for num in range(10, -1, -3):
        if num > 0:
            print(f"{num} is a positive number")
        else:
            print(f"{num} is not a positive number")

# Run the function
iterate_numbers()

10 is a positive number
7 is a positive number
4 is a positive number
1 is a positive number


32. Write a python program to print the following pattern.  
1  
1 1  
1 1 1  
1 1 1 1  
1 1 1 1 1  

In [ ]:
def print_pattern():
    for i in range(1, 6):
        print("1 " * i)

print_pattern()

1 
1 1 
1 1 1 
1 1 1 1 
1 1 1 1 1 


33. Write a Python program that accepts user inputs.

In [ ]:
name = input("Enter your name: ")
age = input("Enter your age: ")

print(f"Ay, {name}! Tumar {age} boyosh hoye gese. Ekhono biya koro nai???")

Enter your name: Joy
Enter your age: 23
Ay, Joy! Tumar 23 boyosh hoye gese. Ekhono biya koro nai???


34. Write a loop in Python that prints only the even numbers from 1 to 10.

In [ ]:
for number in range(1, 11):
    if number % 2 == 0:
        print(number)

2
4
6
8
10


35. Write a Python function to calculate the average of two integers.

In [ ]:
def calculate_average(a, b):
    return (a + b) / 2

num1 = int(input("Enter the first integer: "))
num2 = int(input("Enter the second integer: "))
average = calculate_average(num1, num2)
print("The average is:   ", average)

Enter the first integer: 50
Enter the second integer: 50
The average is:    50.0


36. Write a Python program that keeps on accepting a number from the user until the user enters ‘-1. Display the sum and average of all the numbers.

In [ ]:
def sum_and_average():
    total = 0
    count = 0

    while True:
        number = int(input("Enter a number: "))
        if number == -1:
            break
        total += number
        count += 1

    if count > 0:
        average = total / count
        print("Sum of all numbers:", total)
        print("Average of all numbers:", average)
    else:
        print("No numbers were entered.")

sum_and_average()


Enter a number: 5
Enter a number: 10
Enter a number: -1
Sum of all numbers: 15
Average of all numbers: 7.5


37. Write a Python program that reverses a given list without using the built-in reverse() method. Print the reversed list.

In [ ]:
def reverse_list(lst):
    reversed_list = []
    for i in range(len(lst) - 1, -1, -1):
        reversed_list.append(lst[i])
    return reversed_list

sample_list = [1, 2, 3, 4, 5]
reversed_list = reverse_list(sample_list)
print("Reversed List:", reversed_list)

Reversed List: [5, 4, 3, 2, 1]


38. Write a Python program that finds and prints the common elements between two lists.

In [ ]:
def find_elements(list1, list2):
    common_elements = [element for element in list1 if element in list2]
    return common_elements

list1 = ['Hi', 2, 'apple', 4, 5, 10]
list2 = [4, 5, 6, 'Hi', 8, 'chocolate']
print("Common elements:", find_elements(list1, list2))

Common elements: ['Hi', 4, 5]


39. Write a Python program that uses a loop to iterate over a range of numbers. The range should start from 0 and decrease by 2 each time until it reaches a number less than -10. For each number in the range, print whether it is an even number or an odd number.

In [ ]:
for num in range(0, -12, -2):
    if num % 2 == 0:
        print(f"{num} is even")
    else:
        print(f"{num} is odd")

0 is even
-2 is even
-4 is even
-6 is even
-8 is even
-10 is even


41. Write a loop in Python that prints the numbers from 1 to 10.

In [ ]:
for i in range(1, 11):
    print(i)

42. How do you create a dictionary in Python? Provide an example.

In [ ]:
student_info = {'name': 'Ramim',
                'age': 22,
                'major': 'Computer Science'}
print(student_info)

{'name': 'Ramim', 'age': 22, 'major': 'Computer Science'}


43. Write a Python code snippet that checks if a number is even or odd. The number will be provided by the user. So you have to take a number as input then check if the number is even or odd.

In [ ]:
number = int(input("Enter a number: "))

if number % 2 == 0:
    print(f"{number} is even.")
else:
    print(f"{number} is odd.")

Enter a number: 20
20 is even.


44. Write a Python program that prints the multiplication from 1 to 10.

In [ ]:
for i in range(1, 11):
    for j in range(1, 11):
        print(f"{i} x {j} = {i * j}")
    print()

45. Write a Python code snippet that checks if a number is even or odd.

In [ ]:
number = int(input("Enter a number: "))

if number % 2 == 0:
    print(f"{number} is even.")
else:
    print(f"{number} is odd.")

Enter a number: 44
44 is even.


46. What is the output of the following code?  
```
for num in range(10):
if num % 2 == 0:
continue
print(num)
```

In [ ]:
#Output
#1
#3
#5
#7
#9

47. What is the output of the following code?  
```
s = "Welcome"
print(s)
s = s + " to"
print(s)
s += " Python!"
print(s)
s = s[:16]
print(s)
s = s.replace("Welcome", "introduction")
print(s)
```

In [ ]:
#output

#Welcome
#Welcome to
#Welcome to Python!
#Welcome to Python!
#introduction to Python!

48. What is the output of the following code?  
```
x = "introduction to Python"
movie = "Inception"
book = "Sherlock Holmes"
poem = "the sun rises over the quiet town"   
print(x.islower())
print(x.isupper())
print(movie.startswith("inception"))
print(movie.endswith("Journey"))
print(book.istitle())
print(poem.istitle())
print(book[-11:-4])
```

In [ ]:
#Output

#False
#False
#False
#False
#True
#False
#Holm